from lib.geopy.geocoders.bing import Bing
from lib.geopy.geocoders.google import Google
from lib.geopy.geocoders.googlev3 import GoogleV3
from lib.geopy.geocoders.dot_us import GeocoderDotUS
from lib.geopy.geocoders.geonames import GeoNames
from lib.geopy.geocoders.wiki_gis import MediaWiki
from lib.geopy.geocoders.wiki_semantic import SemanticMediaWiki
from lib.geopy.geocoders.yahoo import Yahoo
from lib.geopy.geocoders.openmapquest import OpenMapQuest
from lib.geopy.geocoders.mapquest import MapQuest